### ISSUE TITLE
Checkbox weird behavior

### ISSUE THREAD

**Issue by JZL** [Freyskeyd/gulp-prompt#14]
I'm sorry if this is a stupid question but I can't seem to get it to work. I was trying the basic checkbox tutorial and my code is

```
gulp.task('spellcheck', function() {
    return gulp.src('app/index.html')
        .pipe($.prompt.prompt({
            type: 'checkbox',
            name: 'bump',
            message: 'What type of bump would you like to do?',
            choices: ['Yes', 'No']
        }, function(res) {
            //value is in res.bump (as an array) 
            console.log(JSON.stringify(res))
            console.log(JSON.stringify(res.bump))
            if(**** == "Yes"){
            }
        })) 
});
```

What would I put in for the asterisks, the first console returns `{"bump":[]}` and the second (obviously) returns `[]`. What am I missing?

**Comment by corbanCloud** [comment]
I thought I was having the same issue. After you use the arrow keys to navigate to your choice, you have to press space to select it.

**Comment by strunkie30** [comment]
change type: 'checkbox' to type: 'list' if you want a radio interaction.

**Comment by hottehead** [comment]
I see weird behaviour too. Maybe its because of the shell one uses. I am using ohmyzsh.

> [?] What type of update do you want to do? (Use arrow keys)
❯ revision 
  minor 
  major   major [?25l

--> The last option is repeated plus obscure smybols. I cant change options with arrow keys. And I have to confirm with enter key instead of space.

> [?] What type of update do you want to do? revision
[?25h

--> this is what happens if I press enter.

In the end I went with type "rawlist". This gives the oldschool numbered choices and works.

**Comment by shannonlal** [comment]
I am going to close this issue since it seems like be a work around with the rawlist (see hottehead comment on Mar 6, 2016).  It also seems like this is only on ohmyzsh terminal.  If this is a higher priority or someone wants us to look into this we can re-open the issue
