### ISSUE TITLE
Process not exiting

### ISSUE THREAD

**Issue by hottehead** [Freyskeyd/gulp-prompt#24]
The process does not exit. 

**Minimal Example**

``` javascript
gulp.task('test', function() {
    return gulp.src('/')
        .pipe(prompt.confirm('Are you ready for Gulp?'));
});
```

**Result**

> [15:32:11] Starting 'test'...
> [?] Are you ready for Gulp? (y/N) Y
> [?] Are you ready for Gulp? Yes
> [15:32:12] Finished 'test' after 917 ms

But the process itself runs forever. Am I doing something wrong here or is this simply a bug?

**Comment by Toilal** [comment]
No problem here

**Comment by yuricamara** [comment]
If you want to finish the process without use 'gulp.src('/')', check the issue #22.

**Comment by shannonlal** [comment]
I did some testing on this tonight and was not able to reproduce the issue.  Within the gulp-prompt project I ran the following:
```js
var gulp = require('gulp');
var prompt = require( './index');

gulp.task('test', function() {
    return gulp.src('/')
        .pipe(prompt.confirm('Are you ready for Gulp?'));
});

```
```{r, engine='bash', code_block_name}
This was the output:
[20:04:37] Using gulpfile /gulpfile.js
[20:04:37] Starting 'test'...
? Are you ready for Gulp? 
```
In a separate terminal I checked to see if the gulp process was still running and I got the following:
```{r, engine='bash', code_block_name}
ps -ef | grep gulp
  501 95606 93438   0  8:04PM ttys002    0:00.61 gulp
  501 95609 95287   0  8:04PM ttys007    0:00.00 grep gulp
```

In the first terminal I complete the gulp task by enter Y and I see the following output
```{r, engine='bash', code_block_name}
? Are you ready for Gulp? Yes
[20:04:51] Finished 'test' after 14 s
```

In the other terminal I check to see if the gulp process is still running and I only see the grep command running

```{r, engine='bash', code_block_name}
01 95614 95287   0  8:04PM ttys007    0:00.00 grep gulp
```

I am going to close of this issue since it has been open for a while and we have not being able to reproduce it.  If anyone is able to provide more information please feel fee to reopen the ticket and add some more information.

**Comment by pala-opentext** [comment]
issue is there while running in command prompt, in bash shell issue is not appearing.
